/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sample_management;
import db_connect.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
//import addFiles;
/**
 *
 * @author nazal
 */
public class addFileNew extends javax.swing.JFrame {

    /**
     * Creates new form addFileNew
     */
    public addFileNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file_name = new javax.swing.JLabel();
        file_type = new javax.swing.JLabel();
        file_name_field = new javax.swing.JTextField();
        file_type_select = new javax.swing.JComboBox<>();
        description = new javax.swing.JLabel();
        visibility = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        description_field = new javax.swing.JTextArea();
        visibility_select = new javax.swing.JComboBox<>();
        file_upload = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        file_name.setText("File Name");
        getContentPane().add(file_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 55, 97, 25));

        file_type.setText("FIle Type");
        getContentPane().add(file_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 98, 97, 24));
        getContentPane().add(file_name_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 58, 258, 28));

        file_type_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Folder", "Video", "PDF", "Image" }));
        getContentPane().add(file_type_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 98, -1, -1));

        description.setText("Description");
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 148, 97, 29));

        visibility.setText("Visibility");
        getContentPane().add(visibility, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 284, 97, 27));

        description_field.setColumns(20);
        description_field.setRows(5);
        jScrollPane2.setViewportView(description_field);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 148, 258, 113));

        visibility_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Public", "Private" }));
        getContentPane().add(visibility_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 285, 84, -1));
        getContentPane().add(file_upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 98, 179, 24));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/save-icon--1.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 340, 84, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/Close.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 340, 100, -1));

        jPanel1.setBackground(new java.awt.Color(255, 226, 173));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Add New File");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        new addFiles().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    String fileName = file_name_field.getText();
    String fileType = (String) file_type_select.getSelectedItem();
    String fileUploaded = file_upload.getText();
    String desc = description_field.getText();
    int visibility;
    if ("public".equalsIgnoreCase((String) visibility_select.getSelectedItem())) {
        visibility = 1;
    } else {
        visibility = 0;
    }

    try {
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();

        // Get the logged-in user's name from the login class
        String userName = new login().user_name;
        userName = "test1";

        // Retrieve 'name' and 'role' based on the logged-in user
        String selectQuery = "SELECT name, role FROM files WHERE name = ?";
        PreparedStatement selectStatement = con.prepareStatement(selectQuery);
        selectStatement.setString(1, userName);
        ResultSet selectResult = selectStatement.executeQuery();

        // Check if the user was found and retrieve 'name' and 'role'
        String name = null;
        String role = null;
        if (selectResult.next()) {
            name = selectResult.getString("name");
            role = selectResult.getString("role");
        }

        // Check if the file_name already exists in the database
        String checkQuery = "SELECT COUNT(*) FROM files WHERE file_name = ? && name = ?";
        PreparedStatement checkStatement = con.prepareStatement(checkQuery);
        checkStatement.setString(1, fileName);
        checkStatement.setString(2, userName);
        ResultSet checkResult = checkStatement.executeQuery();
        checkResult.next();
        int count = checkResult.getInt(1);

        if (count > 0) {
            // The file_name already exists, display an error message
            JOptionPane.showMessageDialog(null, "File name already exists. Please choose a different file name.");
        } else {
            // The file_name is unique, proceed with the insertion
            String insertQuery = "INSERT INTO files (file_name, file_type, file, description, public_or_private, name, role) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement = con.prepareStatement(insertQuery);
            preparedStatement.setString(1, fileName);
            preparedStatement.setString(2, fileType);
            preparedStatement.setString(3, fileUploaded);
            preparedStatement.setString(4, desc);
            preparedStatement.setInt(5, visibility);
            preparedStatement.setString(6, name); // Set 'name' from the select query
            preparedStatement.setString(7, role); // Set 'role' from the select query

            int rowsInserted = preparedStatement.executeUpdate();

            if (rowsInserted > 0) {
                // Row inserted successfully
                JOptionPane.showMessageDialog(null, "Added successfully");
                setVisible(false);
                new addFiles().setVisible(true);
            } else {
                // No rows inserted, display an error message
                JOptionPane.showMessageDialog(null, "Error occurred while inserting the record.");
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
    }

    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addFileNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addFileNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addFileNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addFileNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addFileNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel description;
    private javax.swing.JTextArea description_field;
    private javax.swing.JLabel file_name;
    private javax.swing.JTextField file_name_field;
    private javax.swing.JLabel file_type;
    private javax.swing.JComboBox<String> file_type_select;
    private javax.swing.JTextField file_upload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton save;
    private javax.swing.JLabel visibility;
    private javax.swing.JComboBox<String> visibility_select;
    // End of variables declaration//GEN-END:variables
}
