/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sample_management;

import javax.swing.JOptionPane;

/**
 *
 * @author nazal
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
private starredPage starredPageInstance;
private addFiles addFilesInstance;
private homePage homePageInstance;
private profNotes prof;
public static int flag = 0;

    public home() {
    initComponents();
    
    starredPageInstance = new starredPage();
    addFilesInstance = new addFiles();
    homePageInstance = new homePage();
    prof = new profNotes();          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myFiles = new javax.swing.JButton();
        starred = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        prof_notes = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myFiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/add diag.png"))); // NOI18N
        myFiles.setText("My Files");
        myFiles.setPreferredSize(new java.awt.Dimension(170, 40));
        myFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myFilesActionPerformed(evt);
            }
        });
        getContentPane().add(myFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 60));

        starred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/star_f.png"))); // NOI18N
        starred.setText("Starred");
        starred.setPreferredSize(new java.awt.Dimension(170, 40));
        starred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starredActionPerformed(evt);
            }
        });
        getContentPane().add(starred, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 60));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/exit.png"))); // NOI18N
        logout.setText("Logout");
        logout.setPreferredSize(new java.awt.Dimension(170, 40));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, 60));

        prof_notes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/prof.png"))); // NOI18N
        prof_notes.setText("Prof Notes");
        prof_notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prof_notesActionPerformed(evt);
            }
        });
        getContentPane().add(prof_notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 442, 170, 60));

        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/home.png"))); // NOI18N
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        getContentPane().add(home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 87, 170, 80));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 90)); // NOI18N
        jLabel2.setText("Edu Share");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 620, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/main_background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    logout code
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Confirm Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            
            setVisible(false);
         prof.setVisible(false); 
         addFilesInstance.setVisible(false);
         homePageInstance.setVisible(false);
         starredPageInstance.setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

//    visible when clicked
    private void myFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myFilesActionPerformed
        // TODO add your handling code here:
// Hide other pages
    starredPageInstance.setVisible(false);
    homePageInstance.setVisible(false);
    prof.setVisible(false);
    // Show the 'addFiles' page
    addFilesInstance.setVisible(true);
    }//GEN-LAST:event_myFilesActionPerformed

    private void starredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starredActionPerformed
        starredPageInstance.populateStarTableWithData();
        prof.setVisible(false);
        addFilesInstance.dispose(); 
        addFilesInstance.setVisible(false);
         homePageInstance.setVisible(false);
    // Show the 'starredPage' page
    starredPageInstance.setVisible(true);
    }//GEN-LAST:event_starredActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
        new homePage().setVisible(true);
        addFilesInstance.setVisible(false);
        prof.setVisible(false);
        starredPageInstance.setVisible(false);
    }//GEN-LAST:event_home_btnActionPerformed

    private void prof_notesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prof_notesActionPerformed
        // TODO add your handling code here:
        prof.setVisible(true);
    starredPageInstance.setVisible(false);
    homePageInstance.setVisible(false);
//    prof.setVisible(false);
    // Show the 'addFiles' page
    addFilesInstance.setVisible(false);
    }//GEN-LAST:event_prof_notesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        homePage h = new homePage();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
                int flag = 0;
                if(flag==0){
                    flag = 1;
                h.setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton myFiles;
    private javax.swing.JButton prof_notes;
    private javax.swing.JButton starred;
    // End of variables declaration//GEN-END:variables
}
