/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sample_management;

import javax.swing.JOptionPane;

/**
 *
 * @author nazal
 */
public class profPage extends javax.swing.JFrame {

    /**
     * Creates new form profPage
     */
    private homePage h = new homePage();
    private addStudent a = new addStudent();
    private starredPage starredPageInstance;
    private addFiles addFilesInstance;
    private homePage homePageInstance;
    private profNotes prof;
    private addStudent addstd;
    public profPage() {
        
        initComponents();
        starredPageInstance = new starredPage();
        addFilesInstance = new addFiles();
        homePageInstance = new homePage();
        prof = new profNotes();         
        addstd = new addStudent();
        this.close_btn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbt_clr = new javax.swing.JButton();
        new_stdnt1 = new javax.swing.JButton();
        home = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dbt_clr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/doubt.png"))); // NOI18N
        dbt_clr.setText("Doubt Clearence Panel");
        dbt_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbt_clrActionPerformed(evt);
            }
        });
        getContentPane().add(dbt_clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 270, 90));

        new_stdnt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/add.png"))); // NOI18N
        new_stdnt1.setText("Add New Student");
        new_stdnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_stdnt1ActionPerformed(evt);
            }
        });
        getContentPane().add(new_stdnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 270, 90));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/home.png"))); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 270, 80));

        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/Close.png"))); // NOI18N
        close_btn.setText("close");
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        getContentPane().add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 90, -1, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/exit.png"))); // NOI18N
        logout.setText("Logout");
        logout.setPreferredSize(new java.awt.Dimension(170, 40));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 630, 270, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample_management/prof_back.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbt_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbt_clrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbt_clrActionPerformed

    private void new_stdnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_stdnt1ActionPerformed
        // TODO add your handling code here:
        a.setVisible(true);
    }//GEN-LAST:event_new_stdnt1ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.close_btn.setVisible(true);
        h.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        this.close_btn.setVisible(false);
        h.setVisible(false);
    }//GEN-LAST:event_close_btnActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Confirm Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){

            setVisible(false);
            prof.dispose();
            addstd.setVisible(false);
            addFilesInstance.setVisible(false);
            homePageInstance.setVisible(false);
            starredPageInstance.setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_btn;
    private javax.swing.JButton dbt_clr;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton new_stdnt1;
    // End of variables declaration//GEN-END:variables
}
